# Generated by Django 5.0.2 on 2024-04-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_entry_pannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingcode', models.CharField(max_length=100)),
                ('passengername', models.CharField(max_length=100)),
                ('prize', models.CharField(max_length=100)),
                ('issueby', models.CharField(max_length=100)),
                ('eticketnumber', models.CharField(max_length=100)),
                ('passportnumber', models.CharField(max_length=100)),
                ('ticketfees', models.CharField(max_length=100)),
            ],
        ),
    ]
