# Generated by Django 5.0.2 on 2024-04-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner_Table',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('createdat', models.CharField(max_length=100)),
                ('updatedat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Brand_Table',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cartegoryname', models.CharField(max_length=100)),
                ('brandname', models.CharField(max_length=100)),
                ('createdat', models.CharField(max_length=100)),
                ('updatedat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category_Table',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('createdat', models.CharField(max_length=100)),
                ('updatedat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Table',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('createdat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Delifees_Table',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('regionname', models.CharField(max_length=100)),
                ('township', models.CharField(max_length=100)),
                ('delieryfees', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('createdat', models.CharField(max_length=100)),
                ('updatedat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Information_Table',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=100)),
                ('createdat', models.CharField(max_length=100)),
                ('updatedat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order_table',
            fields=[
                ('orderid', models.IntegerField(primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('updatedat', models.CharField(max_length=100)),
                ('orderdate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Table',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('paymenttype', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('createdat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Table',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cartegory', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('createdat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region_table',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('regionname', models.CharField(max_length=100)),
                ('createdat', models.CharField(max_length=100)),
                ('updatedat', models.CharField(max_length=100)),
            ],
        ),
    ]
