# Generated by Django 5.0.2 on 2024-04-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_banner_table_brand_table_category_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_table',
            name='stock',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
