# Generated by Django 5.0.2 on 2024-04-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_product_table_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_table',
            name='brand',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
