# Generated by Django 5.0.2 on 2024-04-03 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_product_table_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_table',
            old_name='cartegory',
            new_name='category',
        ),
    ]
