# Generated by Django 5.0.2 on 2024-04-03 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_cartegory_product_table_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Delifees_Table',
            new_name='Delifee_Table',
        ),
    ]
