# Generated by Django 5.0.2 on 2024-04-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_delifees_table_delifee_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delifee_table',
            old_name='delieryfees',
            new_name='deliveryfees',
        ),
    ]
