# Generated by Django 5.0.2 on 2024-04-14 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_delieryfees_delifee_table_deliveryfees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand_table',
            old_name='cartegoryname',
            new_name='categoryname',
        ),
    ]
